Lambda-School-Labs/bg-emotion-tracker-fe

- package-lock.json
- package.json
- src/__tests__/Home.test.js
- src/__tests__/RenderHomePage.test.js
- src/components/pages/Home/RenderHomePage.js
*Added the styled-components package
Main Changes to Dashboard:
*Added navbar with picture icon, title and dropdown menu
*Added sample data that will be worked on by later iterations
*Import CSV file button added at bottom
- [] Complete, but not tested (may need new tests)
> Main Dashboard Redesign 

- .env.sample
- package-lock.json
- package.json
- src/components/pages/Home/RenderHomePage.js
- src/components/pages/QRCodeGenerator/QRCodeGenerator.js
- src/components/pages/QRCodeGenerator/index.js
- src/index.js
- src/utils/qrGenerator.js
*Added qrcode.react npm package
*Added QRGenerator component to utilities with such functionality as:
- rendering QR Code in DOM
- giving ability to download QR Code in JPEG format  
*Added route for QRGenerator component for testing purposes
> Sample QR generator

- README.md
Updated the README to reflect the project so far!
> updated readme with current info

- package-lock.json
- src/components/pages/MemberScanner/MemberScannerContainer.js
- src/components/pages/MemberScanner/RenderMemberScanner.js
- src/components/pages/MemberScanner/index.js
- src/components/pages/QRCodeReader/QRCodeReader.js
- src/index.js
*Creating MemberScanner component
*Adding QRCodeReader to MemberScanner
*Adding QR data saving functionality
> Member Scanner feature

- src/components/pages/MemberScanner/RenderMemberScanner.js
- src/components/pages/QRCodeReader/QRCodeReader.js
*Error handling feature for Member QR scaner
> Adding error handling to Member Scanner

- src/api/index.js
- src/components/pages/ActivitySelect/RenderActivitySelect.js
- src/components/pages/EmojiConfirmRedirect/RenderEmojiConfirmRedirect.js
- src/components/pages/EmojiSelectCheck/RenderEmojiSelectCheck.js
- src/components/pages/MemberScanner/RenderMemberScanner.js
- src/components/pages/YDPDashboard/YDPDashboardPage.js
Quick Update for formatting the added pages!
> Feature/ydp pages/robg

- src/components/pages/ActivitySelect/RenderActivitySelect.js
- src/components/pages/EmojiConfirmRedirect/RenderEmojiConfirmRedirect.js
- src/components/pages/EmojiSelectCheck/RenderEmojiSelectCheck.js
- src/components/pages/MemberScanner/RenderMemberScanner.js
- src/styles/styles.css
Changed:
-Changed The Emoji Page selector.
-Styling to center elements.
-CSS Override started but not finished - for Emoji Page.
Needed
-Investigate QR Centering Bug.
-BackEnd Connections.
> StylingPass - Centering, Sizes, and Emoji Page Changes

- src/components/pages/ActivitySelect/RenderActivitySelect.js
- src/components/pages/EmojiSelectCheck/EmojiSelectCheck.js
- src/components/pages/EmojiSelectCheck/RenderEmojiSelectCheck.js
- src/components/pages/MemberScanner/ManualMemberInput.js
- src/components/pages/MemberScanner/RenderMemberScanner.js
- src/components/pages/YDPDashboard/YDPDashboardPage.js
- src/index.js
- src/state/contexts/index.js
* Adding Member context to state management
* Fixing problems with sending member reaction to back-end
> Member reaction functionality fix

- src/components/pages/AdminDashboard/AdminDashboardPage.js
- src/components/pages/ClubDirectorDashboard/ClubDirectorDashboardPage.js
- src/components/pages/YDPDashboard/YDPDashboardPage.js
Simple change to update names for each user dashboard
> Updated titleName for dashboards

- src/components/pages/MemberScanner/RenderMemberScanner.js
* Fixes to member security
* Invalid Members will not be able to proceed into emoji page.
> Fixed Valid Member Check - Complete Flow Working

- src/components/pages/EmojiConfirmRedirect/RenderEmojiConfirmRedirect.js
- src/components/pages/EmojiSelectActivity/RenderEmojiSelectActivity.js
- src/components/pages/MemberScanner/ManualMemberInput.js
- src/components/pages/MemberScanner/RenderMemberScanner.js
The main loop now switches correctly to the emoji selection page, and the memberId context is set correctly.
> main loop fixed

- src/components/pages/MemberScanner/RenderMemberScanner.js
adds media query for desktop to fix the scanner size
> adds media query for desktop

- src/components/ReportsWidget/AllEmotionsFilter.js
- src/components/ReportsWidget/ChartByActivity.js
- src/components/ReportsWidget/ChartByMember.js
- src/components/ReportsWidget/ChartType.js
Added back toggling all emotions for member morale.
> added back the toggle for all emotions for member morale

- src/components/pages/EmojiConfirmRedirect/RenderEmojiConfirmRedirect.js
- src/components/pages/EmojiSelectActivity/RenderEmojiSelectActivity.js
- src/styles/styles.less
* Tweaks emojis to zoom from center instead of top-left
* Minor Styling changes
> Small Emoji select tweaks

- src/components/common/Buttons/StyledBtn.js
- src/components/pages/ActivitySelect/RenderActivitySelect.js
- src/components/pages/EmojiConfirmRedirect/RenderEmojiConfirmRedirect.js
- src/components/pages/Home/HomeContainer.js
- src/components/pages/YDPDashboard/YDPDashboardPage.js
- src/state/actions/index.js
*Fixing some 'red' react warnings in the console output.
> Warning fixing 

- src/components/ReportsWidget/ChartByActivity.js
Fixes the minor widget bug mentioned
> attendance -> checkin/out regex

- src/components/common/Logout.js
- src/state/contexts/index.js
*Adding a logo image to a PDF file
> resets user context to {}

- public/index.html
- src/components/pages/MemberScanner/RenderMemberScanner.js
Fixed the typo that messed up the page switching logic
> Bug fixes/activity type

- public/index.html
> added commented code for disabling reactdevtools

- src/components/pages/EmojiSelectActivity/RenderEmojiSelectActivity.js
- src/components/pages/EmojiSelectCheck/RenderEmojiSelectCheck.js
* Changed / Tweaked the CSS styling and formatting for Emoji Selection.
> Fixed/Tweaked Emoji Selection Style Formatting

- src/components/pages/EmojiConfirmRedirect/RenderEmojiConfirmRedirect.js
- src/components/pages/EmojiSelectActivity/RenderEmojiSelectActivity.js
- src/components/pages/EmojiSelectCheck/RenderEmojiSelectCheck.js
- src/styles/styles.less
* Changed / Tweaked the CSS styling and formatting for Emoji Pages.
* Now Including the redirect page!
> Feature/emoji formatting III

- src/styles/styles.less
The purpose of the PR is to fix a visual bug that would hide some content of the okta widget if a user entered in the wrong credentials. [Trello card ](https://trello.com/c/LndeSTyk)
> Fixes the okta widget visual bug(content overflow) in styles.less

- src/index.js
- src/utils/HiddenRoute.js
I added one file and edited one file. in utils i added HiddenRoute.js discription is in the comments of the file.  Second I imported it to the main index.js and wrapped the login route in it so the user will be redirected to the dashboard if they try to navigate to login while a token is in local storage. 
Wrote some basic code to add images to the dashboards as a proof of concept
To have something to show that is closer to what the final product may look like
Any relevant links or images / screenshots  
image
[] Yes
Checklist …
> Hidden route add

- src/components/common/Logout.js
Removes all items from local storage upon logout
removed storage of "role"
To secure the site.  The user role was not being deleted from the LS.  
[x] Bug Fix
[x] Yes
Checklist
[] I have made corresponding changes to the documentation  
[x] My changes generate no new warnings  
[x] There are no …
> removes all items from local storage upon logout

- src/components/pages/Leaderboard/Leaderboard.css
- src/components/pages/Leaderboard/RenderLeaderboard.js
Description
Created toggle capability on bottom of Leaderboard. Completed CSS for Leaderboard. 
Added code to the Leaderboard components.
Why was this work done?
To create a toggle to move between data points on the leaderboard. 
Change Status
[ ] Completed, ready to review, and merge
[x] Yes
Checklist
[x] My code follows the style guidelines of this project
[x] I have performed a self-review of my own code
[ ] My code has been reviewed by at least one peer
[X] I have commented on my code, particularly in hard-to-understand areas
[ ] I have made corresponding changes to the documentation
[x] My changes generate no new warnings
> Toggle added to Leaderboard, css complete

- src/components/pages/AdminDashboard/AdminDashboardPage.js
- src/components/pages/DashboardAlerts/AlertsDummyData.js
- src/components/pages/DashboardAlerts/DashboardAlerts.css
- src/components/pages/DashboardAlerts/DashboardAlertsContainer.js
- src/components/pages/DashboardAlerts/RenderDashboardAlerts.js
- src/components/pages/DashboardAlerts/index.js
I created a new component, DashboardAlerts, and added it to the Admin sider.  One function to combine  all locations into one   object with the value of the number of times the location appears.  This is for the flags in the alerts side bar.  The flags have the functionality to redirect to another component but that is not set up yet.
> Alerts page

- src/components/pages/Leaderboard/Leaderboard.css
Leaderboard styles changed at meeting
> Updated Leaderboard styles at StandUp

- src/components/pages/Leaderboard/Leaderboard.css
No more hover on <li> items. Spacing issues fixed. Smooth transitions added.
> Final leaderboard css. Ready for 6/14 meeting

- src/components/pages/Alerts/Alerts.css
- src/components/pages/Alerts/RenderAlerts.js
- src/components/pages/Leaderboard/Leaderboard.css
Created template for Alerts page. More style changes for Leaderboard.
> Leaderboard and Alerts Style Changes

- src/components/pages/DashboardAlerts/AlertsDummyData.js
- src/components/pages/DashboardAlerts/DashboardAlerts.css
- src/components/pages/DashboardAlerts/RenderDashboardAlerts.js
This is a work in progress.
Makes axios call to set negative reactions to state and creates badges that update live. 
Axios calls on component. css for flags.  tweaked function to count the occurrences per club location.  
to show the badges on the clubs and have the  negative sentiment as per the stakeholders request.
**Please delete options that are not relevant.**  
[x] Yes
Checklist
[] I have commented my code, …
>  the badges update with data live

- src/components/pages/Alerts/Alerts.css
- src/components/pages/Alerts/RenderAlerts.js
The template for the Alerts page is complete. Extra/unnecessary code removed. I utilized the <Tabs> component to create toggle capability for the Alerts page. The sections for the alerts are ready. Will create a new component called Notifications to populate the boxes already created.
> Alerts Page completed and polished

- src/api/index.js
- src/components/pages/AdminDashboard/AdminDashboardPage.js
- src/components/pages/Clubs/ViewClubs.js
- src/components/pages/DashboardAlerts/RenderDashboardAlerts.js
- src/state/actions/index.js
- src/state/contexts/index.js
I removed the api calls on the components and put it on the dashboard to allow other components to use the state.
Fixed context and actions and rewired the api call.  
Rewiring  on the page render allows many components to use the state. 
[] New feature (non-breaking change which adds functionality)
[x] Bug fix
[x] Yes
Checklist
[] I have made corresponding …
> rewired the api calls to happen on the dashboard

- src/api/index.js
- src/components/pages/AdminDashboard/AdminDashboardPage.js
- src/components/pages/DashboardAlerts/RenderDashboardAlerts.js
- src/components/pages/Leaderboard/RenderLeaderboard.js
Description
Added the axios call for an example on the admindash. Fixed issues with leaderboard. 
Fixed the get request on the AdminDash
Why was this work done?
To stop using dummy data for components. 
Please delete options that are not relevant.
[] New feature (non-breaking change which adds functionality)
[x] Bug fix
Change Status
[x] Yes
Checklist
[x] My code follows the style guidelines of this project
[x] I have performed a self-review of my own code
[] My code has been reviewed by at least one peer
[x] My changes generate no new warnings
> Added axios call to admindash, fixed issues on leaderboard

- src/components/common/Buttons/BackButton.js
- src/components/common/NavBar.js
- src/components/common/NavMenu.js
- src/components/pages/ActivitySelect/RenderActivitySelect.js
- src/components/pages/AdminDashboard/AdminDashboardPage.js
- src/components/pages/Alerts/RenderAlerts.js
- src/components/pages/ClubDirectorDashboard/ClubDirectorDashboardPage.js
- src/components/pages/Clubs/ViewClubs.js
- src/components/pages/DashboardAlerts/RenderDashboardAlerts.js
- src/components/pages/Leaderboard/RenderLeaderboard.js
- src/components/pages/MemberScanner/RenderMemberScanner.js
- src/components/pages/Members/ViewMembers.js
- src/components/pages/Programs/ViewPrograms.js
- src/components/pages/YDPDashboard/YDPDashboardPage.js
- src/styles/styles.css
- src/styles/styles.less
Created NavMenu component. Added Sider with NavMenu inside to all components where NavBar component rendered.
> navbar sider design

- src/api/index.js
- src/components/common/Tabs.js
- src/state/actions/index.js
- src/state/contexts/index.js
Added api call to api file, wrote the action, connected the context, fixed one bug on TABS by removing a <div>
wrote the api call and context to work on the leaderboard.  LEADERBOARD HAS NOT BEEN CONNECTED YET
previously working with dummy data on the leaderboard.  We can start using the api to use live data.
**Please delete options that are not relevant.**  
[x] Bug Fix
[] Yes
Checklist
[x] My code has been reviewed by at least one peer  
[] I have commented my …
> wired up api and context for leaderboard

- src/components/common/NavMenu.js
- src/components/common/Tabs.js
Added badge to nav bar alerts tab and removed a <Div> that was added to TABS.js that was causing a bug.
See description
Fixed bug and showed live counter to see alerts has something in it.
[x] Yes
Checklist
[] I have made corresponding changes to the documentation  
[x] My changes generate no new …
> added badge to nav menu alert

- src/components/pages/Alerts/Alerts.css
- src/components/pages/Alerts/RenderAlerts.js
- src/components/pages/Leaderboard/Leaderboard.css
- src/components/pages/Leaderboard/RenderLeaderboard.js
Description
Wired up context for Alerts and Leaderboard. Data is coming in for both pages. Fixed CSS problems on Leaderboard.
What did you change?
Context added to both pages.
> Context wired up for Leaderboard and Alerts with CSS fixes

- src/components/common/NavMenu.js
- src/components/common/Tab.js
- src/components/common/Tabs.js
- src/components/pages/Alerts/Alerts.css
- src/components/pages/Alerts/RenderAlerts.js
Added badges to the alerts that update with the backend.
wired up the badges to the alerts and added css to display them.
Stakeholder request
[x] Yes
Checklist
[] I have made corresponding changes to the documentation  
[x] My changes generate no new warnings  
>  added alert badges to alert pages and css fixes

- src/components/common/NavBar.js
- src/components/common/NavMenu.js
fixed nav-sider bug on reload, cleaned up navbar component
> fixed navbar

- src/components/common/NavMenu.js
- src/components/common/Tab.js
- src/components/pages/AdminDashboard/AdminDashboardPage.js
- src/components/pages/Alerts/Alerts.css
- src/components/pages/Alerts/RenderAlerts.js
- src/components/pages/Clubs/ViewClubs.js
- src/components/pages/Home/HomeContainer.js
- src/components/pages/Leaderboard/Leaderboard.css
- src/components/pages/Leaderboard/RenderLeaderboard.js
- src/components/pages/Members/ViewMembers.js
Reload problem was fixed on render alerts and a bunch of console.logs removed. 
lots of little things on the pages.  
Fixes reload bugs and css is important!  
**Please delete options that are not relevant.**  
[x] Bug fixes
[x] Yes
Checklist
[] I have made corresponding changes to the documentation  
[x] My changes generate no new warnings  
> Alerts wiring

- src/components/common/NavBar.js
- src/components/pages/Alerts/RenderAlerts.js
- src/components/pages/Clubs/ViewClubs.js
- src/index.js
- src/styles/styles.css
Description
There were a couple of warnings that were cleared up. Also added a spinner to the RenderAlerts component to be shown while the clubs and alerts are being fetched.
What work was done?  
added a key prop to the clubs in ViewClubs.
removed strict mode
Added a spinner while clubs are being fetched
Why was this work done?  
The warnings could possibly cause the deploy to fail
[] New feature (non-breaking change which adds functionality)
[x ] Completed, ready to review and merge  
[ ] Yes
[X] No
Checklist
[X] My code follows the style guidelines of this project  
[X] I have performed a self-review of my own code  
[X] My code has been reviewed by at least one peer  
[] I …
> Fixes a couple of bugs and warnings.

- src/components/pages/Alerts/Alerts.css
- src/components/pages/Alerts/RenderAlerts.js
- src/components/pages/Clubs/ViewClubs.js
Added cards on the the alerts page that displays all negative alerts on cards.
**What work was done?**
Created cards.  Added key to a mapping to please the react gods of keys.  Wrote a function that splits the alerts into an object with key=club name and value= alert
Change Status
[ ] Yes
Checklist
[X] My code follows the style guidelines of this project
[X] I have performed a self-review of my own code
[X] My code has been reviewed by at least one peer
[X] My changes generate no new warnings
[X] There are no merge conflicts …
> Alerts render

- src/api/index.js
- src/components/pages/AdminDashboard/AdminDashboardPage.js
- src/components/pages/Home/HomeContainer.js
- src/state/actions/index.js
- src/state/contexts/index.js
Description
Created graph using Plotly on the AdminDashboard. Context for feedback endpoint added. 
Graph setup for dashboard complete. 
Why was this work done?
CSS and functionality for graphs done. 
Please delete options that are not relevant.
[x] Bug fixes
Change Status
[x] Yes
Checklist
[x] My code follows the style guidelines of this project
[x] I have performed a self-review of my own code
[] My code has been reviewed by at least one peer
[x] My changes generate no new warnings
> Graph setup on AdminDashboard, Feedback context added

- src/components/pages/AdminDashboard/AdminDashboardPage.css
Description
Added admin dashboard css. 
Css for graphs
Why was this work done?
CSS and functionality for graphs done.
Please delete options that are not relevant.
[x] Bug fixes
Change Status
[x] Yes
Checklist
[x] My code follows the style guidelines of this project
[x] I have performed a self-review of my own code
[] My code has been reviewed by at least one peer
[x] My changes generate no new warnings
> AdminDash CSS added

- src/components/pages/AdminDashboard/AdminDashboardPage.js
- src/components/pages/Alerts/RenderAlerts.js
- src/components/pages/Clubs/ImportClubs/AddIndividual.js
- src/components/pages/Home/HomeContainer.js
Description
[x]bug fix
Change Status
[ ] Yes
Checklist
[X] My code follows the style guidelines of this project
[X] I have performed a self-review of my own code
[X] My code has been reviewed by at least one peer
[X] My changes generate no new warnings
[X] There are no merge conflicts (edited)
> fixed stuff with ?

- src/components/pages/AdminDashboard/AdminDashboardPage.js
- src/components/pages/Alerts/RenderAlerts.js
used a span to display the emoji 
Co-authored-by: George <georgehatzigeorgio@zohomail.com>
Co-authored-by: Fidan <fidan.nazimson@gmail.com>
> FE: Display Emoji on alert card

- src/components/common/NavMenu.js
The Club Director doesn't need/ shouldn't have access to Manage Clubs. Only the SuperAdmin needs that.
> Removed Access to Manage Clubs from Club Director

- src/components/pages/Alerts/RenderAlerts.js
Each alert card displays emoji and activity. On hover over the card, a tooltip pops up with additional information, including memberid, activity, time, elapsed time, and emoji. Still need to configure elapsed time properly, Change the color of the card and tooltip depending on elapsed time, and align the cards so they don't wrap or go off the card when there are more than about 6 cards
> Created a card grid system for each club. 

- src/components/pages/ClubsPages/anderson.js
- src/index.js
collab with Shawn, redirected admin dashboard to Anderson club.
> Robert rodriguez

- src/api/index.js
- src/components/pages/Members/ViewMembers.js
Added activate/deactivate button to member table. Added function to update member active status to apis file. Also there is unused commented out code below the component I kept that for reason if it is needed.
> added activate/deactivate functionality to members

- src/components/pages/ReactionsTable/RenderReactionsTable.js
Completed RenderReactions table.  But that component doesn't have any path to be shown. Also fixed context problem.
> completed reactions table

- src/components/pages/Alerts/Alerts.css
- src/components/pages/Alerts/RenderAlerts.js
Put alerts into a table, created css to color background dependant upon elapsed time
> Alerts Page & Styling

- src/api/index.js
- src/components/ReportsWidget/ChartByActivity.js
- src/components/common/Buttons/BackButton.js
- src/components/common/Tabs.js
- src/components/pages/AdminDashboard/AdminDashboardPage.js
- src/components/pages/Alerts/Alerts.css
- src/components/pages/ClubDirectorDashboard/ClubDirectorDashboardPage.js
- src/components/pages/DashboardAlerts/RenderDashboardAlerts.js
- src/components/pages/Home/RenderHomePage.js
- src/components/pages/MemberScanner/ManualMemberInput.js
- src/components/pages/Members/ViewMembers.js
- src/components/pages/Programs/ViewPrograms.js
- src/components/pages/YDPDashboard/YDPDashboardPage.js
Just removed some comment out code or redundant code to clean up the files.
> Kay richards

- src/components/pages/Alerts/Alerts.css
- src/components/pages/Alerts/RenderAlerts.js
Corrected Alerts time display and style
> Alerts.css and RenderAlerts.js

- src/components/pages/Alerts/Alerts.css
- src/components/pages/Alerts/RenderAlerts.js
Further definition of tables, and css design. Left commented out code, as still deciding which option to use to display table data.
> RenderAlerts.js and Alerts.css

- src/components/common/NavMenu.js
- src/components/pages/AdminDashboard/AdminDashboardPage.js
Changed Admin Dashboard title to be Admin Dashboard when Home is clicked and to be club name, if any of clubs is selected. There are some commented out code, I left them in case we need it.
> Changed homepage title toggle

- src/components/common/NavMenu.js
changed the navigation side bar manage reactions upsquare icon to a table icon
> Robert nav icon change

- src/components/common/NavMenu.js
- src/components/pages/AdminDashboard/AdminDashboardPage.js
- src/components/pages/ClubsPages/anderson.css
- src/components/pages/ClubsPages/anderson.js
- src/components/pages/Leaderboard/RenderLeaderboard.js
- src/styles/styles.less
changed the height of the dashboard page and the club page to prevent a scroll bar as mush as possible. smaller screens may show a scroll bar. also added the new endpoint for the plot.
> Robert plot

- src/components/pages/Alerts/Alerts.css
- src/components/pages/Alerts/RenderAlerts.js
Final Admin Alerts page. Still need Club Director Alerts page, and left code for Ant Design Table
> RenderAlerts.js & Alerts.css

- src/components/pages/AdminDashboard/AdminDashboardPage.js
- src/components/pages/Alerts/RenderAlerts.js
Updated AdminDashboard Landing graph, and updated the Alerts page. Commented out the pagination bug, to be resolved later.
> AdminDashboard & Alerts update
